---
- name: Deploy Web App
  hosts: n3
  become: yes

  tasks:
  - name: install Git
    yum: 
      name: git
      state: present

  - name: Host code
    git: 
      repo: https://github.com/JNTGLORY/food3.git
      dest: /var/www/html
      
...        
